// react/src/components/PrintBar.tsx
import { useResumeStore } from '../stores/useResumeStore';

export default function PrintBar() {
  const viewMode = useResumeStore((s) => s.viewMode);
  const toggleViewMode = useResumeStore((s) => s.toggleViewMode);

  const btn: React.CSSProperties = {
    border: '1px solid var(--c-border)',
    background: 'var(--c-card)',
    color: 'var(--t2)',
    padding: '.35rem .9rem',
    borderRadius: 4,
    cursor: 'pointer',
    fontSize: '.78rem',
    fontFamily: 'inherit',
    transition: 'all .15s',
  };

  const primaryBtn: React.CSSProperties = {
    ...btn,
    background: 'var(--c-primary)',
    color: 'var(--c-surface)',
    borderColor: 'var(--c-primary)',
    fontWeight: 500,
  };

  // Entry button (interactive mode)
  if (viewMode !== 'print') {
    return (
      <div style={{ textAlign: 'right', marginBottom: '.3rem' }} className="no-print">
        <button onClick={toggleViewMode} style={{ ...btn, fontSize: '.75rem' }}>
          打印预览
        </button>
      </div>
    );
  }

  // Toolbar (preview mode)
  return (
    <div
      className="print-toolbar"
      style={{
        position: 'sticky', top: 0, zIndex: 50,
        display: 'flex', alignItems: 'center', gap: '.8rem',
        padding: '.6rem 0', marginBottom: '2rem',
        borderBottom: '1px solid var(--c-border)',
        background: 'var(--c-surface)',
        fontSize: '.78rem',
      }}
    >
      <span style={{ color: 'var(--t3)', fontSize: '.75rem', fontFamily: "'JetBrains Mono',monospace" }}>
        打印预览 · A4
      </span>
      <div style={{ flex: 1 }} />
      <button onClick={toggleViewMode} style={btn}>
        退出
      </button>
      <button onClick={() => window.print()} style={primaryBtn}>
        下载 PDF
      </button>
    </div>
  );
}

// vue/src/components/PrintBar.vue
<script setup lang="ts">
import { useResumeStore } from '../stores/useResumeStore';
const store = useResumeStore();

function doPrint() { window.print(); }

const btn = {
  border: '1px solid var(--c-border)', background: 'var(--c-card)', color: 'var(--t2)',
  padding: '.35rem .9rem', borderRadius: '4px', cursor: 'pointer', fontSize: '.78rem',
  fontFamily: 'inherit', transition: 'all .15s',
};
const primaryBtn = { ...btn, background: 'var(--c-primary)', color: 'var(--c-surface)', borderColor: 'var(--c-primary)', fontWeight: 500 };
</script>

<template>
  <div v-if="store.viewMode !== 'print'" class="no-print" style="text-align:right;margin-bottom:.3rem">
    <button @click="store.toggleViewMode()" :style="btn" style="font-size:.75rem">打印预览</button>
  </div>
  <div v-else class="print-toolbar" style="position:sticky;top:0;z-index:50;display:flex;align-items:center;gap:.8rem;padding:.6rem 0;margin-bottom:2rem;border-bottom:1px solid var(--c-border);background:var(--c-surface);font-size:.78rem">
    <span style="color:var(--t3);font-size:.75rem;font-family:'JetBrains Mono',monospace">打印预览 · A4</span>
    <div style="flex:1" />
    <button @click="store.toggleViewMode()" :style="btn">退出</button>
    <button @click="doPrint" :style="primaryBtn">下载 PDF</button>
  </div>
</template>
