// react/src/components/SkillChips.tsx
import { useResume } from '../hooks/useResume';

export default function SkillChips() {
  const { data, activeSkill, toggleSkill, filteredProjects } = useResume();

  return (
    <div className="no-print">
      <div className="section-head">
        <span className="section-label">Skills</span>
        <span className="section-rule" />
      </div>

      {data.skills.map((group) => (
        <div className="skill-group" key={group.category}>
          <span className="skill-cat">{group.category}</span>
          <div className="chip-row">
            {group.items.map((s) => (
              <span
                key={s}
                className={`chip${activeSkill === s ? ' on' : ''}`}
                onClick={() => toggleSkill(s)}
                role="button"
                tabIndex={0}
                aria-pressed={activeSkill === s}
                onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); toggleSkill(s); } }}
              >
                {s}
              </span>
            ))}
          </div>
        </div>
      ))}

      {activeSkill && (
        <p className="filter-hint">
          已筛选「{activeSkill}」— 匹配 {filteredProjects.length} 个项目
          <a onClick={() => toggleSkill(activeSkill)} role="button" tabIndex={0}
            onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); toggleSkill(activeSkill); } }}>
            清除
          </a>
        </p>
      )}
    </div>
  );
}

// vue/src/components/SkillChips.vue
<script setup lang="ts">
import { useResume } from '../composables/useResume';
const { data, activeSkill, toggleSkill, filteredProjects } = useResume();
</script>

<template>
  <div class="no-print">
    <div class="section-head">
      <span class="section-label">Skills</span>
      <span class="section-rule" />
    </div>
    <div v-for="g in data.skills" :key="g.category" class="skill-group">
      <span class="skill-cat">{{ g.category }}</span>
      <div class="chip-row">
        <span v-for="s in g.items" :key="s"
          :class="['chip', { on: activeSkill === s }]"
          @click="toggleSkill(s)">{{ s }}</span>
      </div>
    </div>
    <p v-if="activeSkill" class="filter-hint">
      已筛选「{{ activeSkill }}」— 匹配 {{ filteredProjects.length }} 个项目
      <a @click="toggleSkill(activeSkill!)">清除</a>
    </p>
  </div>
</template>
