// react/src/components/TechFooter.tsx
const TECHS = [
  'React 19', 'TypeScript 5', 'Zustand', 'TanStack Query',
  'React Router 7', 'TailwindCSS 3',
];

export default function TechFooter() {
  return (
    <footer className="tech-ft no-print">
      <span>Built with {TECHS.join(' · ')}</span>
      <span>
        <a href="https://github.com/OneFeiFan/web-resume" target="_blank" rel="noopener noreferrer">GitHub ↗</a>
        {' · '}
        <a href="/about">架构决策 →</a>
      </span>
    </footer>
  );
}

// vue/src/components/TechFooter.vue
<template>
  <footer class="tech-ft no-print">
    <span>Built with Vue 3 · TypeScript 5 · Pinia · Vue Router 4 · TailwindCSS 3</span>
    <span>
      <a href="https://github.com/OneFeiFan/web-resume" target="_blank" rel="noopener noreferrer">GitHub ↗</a>
      · <router-link to="/about">架构决策 →</router-link>
    </span>
  </footer>
</template>
